// Code generated by inspc. DO NOT EDIT.
// source: languages.json

package nlp

const (
	English Language = iota
	Russian
)

type lt struct {
	name, native, iso1, iso3 OL32
}

var (
	__lt_lst = []lt{
		{name: 0, native: 0, iso1: 0, iso3: 0},
		{name: 0, native: 0, iso1: 0, iso3: 0},
	}
	__lt_buf = []byte(`EnglishEnglishenengRussianРусскийrusru`)
)
